[2022-07-15 00:37:10,937] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline scheduled__2022-06-21T15:00:00+00:00 [queued]>
[2022-07-15 00:37:11,418] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline scheduled__2022-06-21T15:00:00+00:00 [queued]>
[2022-07-15 00:37:11,420] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:37:11,423] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-15 00:37:11,425] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 00:37:12,185] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-06-21 15:00:00+00:00
[2022-07-15 00:37:12,773] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-07-15 00:37:13,008] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-06-21T15:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpwfjx7y79', '--error-file', '/tmp/tmpz41x7rac']
[2022-07-15 00:37:13,019] {standard_task_runner.py:80} INFO - Job 14: Subtask pipeline
[2022-07-15 00:37:14,650] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline scheduled__2022-06-21T15:00:00+00:00 [running]> on host 744d078d7eff
[2022-07-15 00:37:16,619] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-06-21T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-21T15:00:00+00:00
[2022-07-15 00:37:16,651] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 70, in pipeline
    df = pd.read_csv(f'{path}/data/train/homework.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yuliv/airflow/airflow_hw/data/train/homework.csv'
[2022-07-15 00:37:16,801] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220621T150000, start_date=20220715T003711, end_date=20220715T003716
[2022-07-15 00:37:16,884] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task pipeline ([Errno 2] No such file or directory: '/Users/yuliv/airflow/airflow_hw/data/train/homework.csv'; 221)
[2022-07-15 00:37:17,244] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-15 00:37:17,813] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
